spring:
  datasource:
    url:        jdbc:mysql://localhost/taco-cloud
    username:   root
    password:   1121
    data:
      - classpath:data.sql
    initialization-mode: always

#  jpa:
#    hibernate:
#      ddl-auto: create-drop