spring:
  datasource:
    url:        jdbc:mysql://localhost/taco-cloud
    username:   root
    password:   1121
    data:
      - classpath:data.sql
    initialization-mode: always

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update