taco:
  discount:
    codes:
      abcdef: 10

  orders:
    pageSize: 10


spring:
  data:
    rest:
      base-path: /api

---
spring:
  profiles: production

  datasource:
    url: jdbc:mysql://localhost:3306/taco-cloud
    username: root
    password: 1121

logging:
  level:
    tacos: warn
